#include "zara/diff/engine.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace zara::diff {

namespace {

struct Fingerprint {
    std::string name;
    std::uint64_t entry = 0;
    std::string normalized_sequence;
    std::unordered_map<std::string, std::size_t> mnemonic_histogram;
    std::size_t block_count = 0;
    std::size_t instruction_count = 0;
    std::size_t call_count = 0;
};

bool is_autogenerated_name(const std::string_view name) {
    return name.rfind("sub_", 0) == 0;
}

Fingerprint build_fingerprint(const analysis::DiscoveredFunction& function) {
    Fingerprint fingerprint{
        .name = function.name,
        .entry = function.entry_address,
        .normalized_sequence = {},
        .mnemonic_histogram = {},
        .block_count = function.graph.blocks().size(),
        .instruction_count = 0,
        .call_count = 0,
    };

    for (const auto& block : function.graph.blocks()) {
        for (const auto& instruction : block.instructions) {
            if (!fingerprint.normalized_sequence.empty()) {
                fingerprint.normalized_sequence.push_back(';');
            }
            fingerprint.normalized_sequence += instruction.mnemonic;
            ++fingerprint.mnemonic_histogram[instruction.mnemonic];
            ++fingerprint.instruction_count;
            if (instruction.kind == disasm::InstructionKind::Call) {
                ++fingerprint.call_count;
            }
        }
    }

    return fingerprint;
}

double ratio_score(const std::size_t lhs, const std::size_t rhs) {
    if (lhs == 0 && rhs == 0) {
        return 1.0;
    }
    if (lhs == 0 || rhs == 0) {
        return 0.0;
    }
    return static_cast<double>(std::min(lhs, rhs)) / static_cast<double>(std::max(lhs, rhs));
}

double mnemonic_similarity(const Fingerprint& lhs, const Fingerprint& rhs) {
    std::size_t intersection = 0;
    std::size_t union_total = 0;
    std::unordered_set<std::string> keys;
    for (const auto& [mnemonic, _] : lhs.mnemonic_histogram) {
        keys.insert(mnemonic);
    }
    for (const auto& [mnemonic, _] : rhs.mnemonic_histogram) {
        keys.insert(mnemonic);
    }

    for (const auto& key : keys) {
        const std::size_t lhs_count =
            lhs.mnemonic_histogram.contains(key) ? lhs.mnemonic_histogram.at(key) : 0;
        const std::size_t rhs_count =
            rhs.mnemonic_histogram.contains(key) ? rhs.mnemonic_histogram.at(key) : 0;
        intersection += std::min(lhs_count, rhs_count);
        union_total += std::max(lhs_count, rhs_count);
    }

    if (union_total == 0) {
        return 1.0;
    }
    return static_cast<double>(intersection) / static_cast<double>(union_total);
}

double similarity(const Fingerprint& lhs, const Fingerprint& rhs) {
    if (lhs.normalized_sequence == rhs.normalized_sequence) {
        return 1.0;
    }

    const double mnemonic_score = mnemonic_similarity(lhs, rhs);
    const double instruction_score = ratio_score(lhs.instruction_count, rhs.instruction_count);
    const double block_score = ratio_score(lhs.block_count, rhs.block_count);
    const double call_score = ratio_score(lhs.call_count, rhs.call_count);
    const bool lhs_named = !is_autogenerated_name(lhs.name);
    const bool rhs_named = !is_autogenerated_name(rhs.name);
    const double name_score = (lhs_named && rhs_named && lhs.name == rhs.name) ? 1.0 : 0.0;

    double score = (0.45 * mnemonic_score) +
                   (0.20 * instruction_score) +
                   (0.15 * block_score) +
                   (0.10 * call_score) +
                   (0.10 * name_score);

    if (lhs_named && rhs_named && lhs.name != rhs.name) {
        score *= 0.5;
    }

    return score;
}

struct CandidateMatch {
    std::size_t before_index = 0;
    std::size_t after_index = 0;
    double similarity = 0.0;
};

}  // namespace

Result Engine::diff(const analysis::ProgramAnalysis& before, const analysis::ProgramAnalysis& after) {
    Result result;

    std::vector<Fingerprint> before_fingerprints;
    before_fingerprints.reserve(before.functions.size());
    for (const auto& function : before.functions) {
        before_fingerprints.push_back(build_fingerprint(function));
    }

    std::vector<Fingerprint> after_fingerprints;
    after_fingerprints.reserve(after.functions.size());
    for (const auto& function : after.functions) {
        after_fingerprints.push_back(build_fingerprint(function));
    }

    std::vector<CandidateMatch> candidates;
    for (std::size_t before_index = 0; before_index < before_fingerprints.size(); ++before_index) {
        for (std::size_t after_index = 0; after_index < after_fingerprints.size(); ++after_index) {
            const double score = similarity(before_fingerprints[before_index], after_fingerprints[after_index]);
            if (score >= 0.35) {
                candidates.push_back(
                    CandidateMatch{
                        .before_index = before_index,
                        .after_index = after_index,
                        .similarity = score,
                    }
                );
            }
        }
    }

    std::sort(
        candidates.begin(),
        candidates.end(),
        [](const CandidateMatch& lhs, const CandidateMatch& rhs) {
            if (std::abs(lhs.similarity - rhs.similarity) > 0.000001) {
                return lhs.similarity > rhs.similarity;
            }
            if (lhs.before_index != rhs.before_index) {
                return lhs.before_index < rhs.before_index;
            }
            return lhs.after_index < rhs.after_index;
        }
    );

    std::vector<bool> before_matched(before_fingerprints.size(), false);
    std::vector<bool> after_matched(after_fingerprints.size(), false);

    for (const auto& candidate : candidates) {
        if (before_matched[candidate.before_index] || after_matched[candidate.after_index]) {
            continue;
        }

        const auto& lhs = before_fingerprints[candidate.before_index];
        const auto& rhs = after_fingerprints[candidate.after_index];
        const ChangeKind kind =
            lhs.normalized_sequence == rhs.normalized_sequence ? ChangeKind::Unchanged : ChangeKind::Modified;

        result.changes.push_back(
            FunctionChange{
                .kind = kind,
                .old_name = lhs.name,
                .new_name = rhs.name,
                .old_entry = lhs.entry,
                .new_entry = rhs.entry,
                .similarity = candidate.similarity,
            }
        );

        before_matched[candidate.before_index] = true;
        after_matched[candidate.after_index] = true;
    }

    for (std::size_t index = 0; index < before_fingerprints.size(); ++index) {
        if (before_matched[index]) {
            continue;
        }

        const auto& fingerprint = before_fingerprints[index];
        result.changes.push_back(
            FunctionChange{
                .kind = ChangeKind::Removed,
                .old_name = fingerprint.name,
                .new_name = {},
                .old_entry = fingerprint.entry,
                .new_entry = 0,
                .similarity = 0.0,
            }
        );
    }

    for (std::size_t index = 0; index < after_fingerprints.size(); ++index) {
        if (after_matched[index]) {
            continue;
        }

        const auto& fingerprint = after_fingerprints[index];
        result.changes.push_back(
            FunctionChange{
                .kind = ChangeKind::Added,
                .old_name = {},
                .new_name = fingerprint.name,
                .old_entry = 0,
                .new_entry = fingerprint.entry,
                .similarity = 0.0,
            }
        );
    }

    std::sort(
        result.changes.begin(),
        result.changes.end(),
        [](const FunctionChange& lhs, const FunctionChange& rhs) {
            if (lhs.kind != rhs.kind) {
                return static_cast<int>(lhs.kind) < static_cast<int>(rhs.kind);
            }
            if (lhs.old_entry != rhs.old_entry) {
                return lhs.old_entry < rhs.old_entry;
            }
            return lhs.new_entry < rhs.new_entry;
        }
    );

    for (const auto& change : result.changes) {
        switch (change.kind) {
        case ChangeKind::Unchanged:
            ++result.unchanged_count;
            break;
        case ChangeKind::Modified:
            ++result.modified_count;
            break;
        case ChangeKind::Added:
            ++result.added_count;
            break;
        case ChangeKind::Removed:
            ++result.removed_count;
            break;
        }
    }

    return result;
}

std::string_view to_string(const ChangeKind kind) noexcept {
    switch (kind) {
    case ChangeKind::Unchanged:
        return "unchanged";
    case ChangeKind::Modified:
        return "modified";
    case ChangeKind::Added:
        return "added";
    case ChangeKind::Removed:
        return "removed";
    default:
        return "unknown";
    }
}

}  // namespace zara::diff
