#include "zara/ai/assistant.hpp"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

#if defined(ZARA_HAS_CURL)
#include <curl/curl.h>
#endif

namespace zara::ai {

namespace {

struct FunctionContext {
    const analysis::DiscoveredFunction* function = nullptr;
    std::vector<std::string> imports;
    std::vector<std::string> strings;
    bool is_entry = false;
    int score = 0;
};

struct ModelFunctionInsight {
    std::uint64_t entry_address = 0;
    std::string suggested_name;
    std::string summary;
    std::vector<std::string> hints;
    std::vector<PatternDetection> patterns;
    std::vector<VulnerabilityHint> vulnerability_hints;
};

std::string normalize_import_name(std::string value) {
    const std::size_t bang = value.rfind('!');
    if (bang != std::string::npos) {
        value = value.substr(bang + 1);
    }
    return value;
}

bool is_autogenerated_name(const std::string_view name) {
    return name.rfind("sub_", 0) == 0;
}

bool contains_value(const std::vector<std::string>& values, const std::string_view needle) {
    return std::find(values.begin(), values.end(), needle) != values.end();
}

bool contains_any_import(const std::vector<std::string>& imports, const std::initializer_list<std::string_view> needles) {
    return std::any_of(
        needles.begin(),
        needles.end(),
        [&](const std::string_view needle) { return contains_value(imports, needle); }
    );
}

bool contains_token(const std::string& value, const std::string_view needle) {
    std::string lowered_value = value;
    std::transform(
        lowered_value.begin(),
        lowered_value.end(),
        lowered_value.begin(),
        [](const unsigned char character) { return static_cast<char>(std::tolower(character)); }
    );
    std::string lowered_needle(needle);
    std::transform(
        lowered_needle.begin(),
        lowered_needle.end(),
        lowered_needle.begin(),
        [](const unsigned char character) { return static_cast<char>(std::tolower(character)); }
    );
    return lowered_value.find(lowered_needle) != std::string::npos;
}

bool strings_contain_token(
    const std::vector<std::string>& strings,
    const std::initializer_list<std::string_view> needles
) {
    return std::any_of(
        strings.begin(),
        strings.end(),
        [&](const std::string& value) {
            return std::any_of(
                needles.begin(),
                needles.end(),
                [&](const std::string_view needle) { return contains_token(value, needle); }
            );
        }
    );
}

std::string sanitize_name(std::string value) {
    for (char& character : value) {
        if (!std::isalnum(static_cast<unsigned char>(character))) {
            character = '_';
        }
    }

    while (!value.empty() && value.back() == '_') {
        value.pop_back();
    }
    if (!value.empty() && std::isdigit(static_cast<unsigned char>(value.front()))) {
        value.insert(value.begin(), '_');
    }
    return value;
}

bool function_contains_address(const analysis::DiscoveredFunction& function, const std::uint64_t address) {
    for (const auto& block : function.graph.blocks()) {
        for (const auto& instruction : block.instructions) {
            if (instruction.address == address) {
                return true;
            }
        }
    }
    return false;
}

std::string choose_summary(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings,
    const bool is_entry
) {
    if (is_entry || std::find(imports.begin(), imports.end(), "__libc_start_main") != imports.end()) {
        return "Runtime entry/bootstrap routine.";
    }
    if (std::find(imports.begin(), imports.end(), "nanosleep") != imports.end()) {
        return "Timing or sleep-related helper.";
    }
    if (std::find(imports.begin(), imports.end(), "strlen") != imports.end() &&
        std::find(imports.begin(), imports.end(), "memcmp") != imports.end()) {
        return "String and memory comparison routine.";
    }
    if (std::find(imports.begin(), imports.end(), "memcmp") != imports.end()) {
        return "Memory comparison routine.";
    }
    if (std::find(imports.begin(), imports.end(), "strlen") != imports.end()) {
        return "String-processing helper.";
    }
    if (!strings.empty()) {
        return "Routine references embedded strings and likely drives user-visible behavior.";
    }

    std::size_t instruction_count = 0;
    for (const auto& block : function.graph.blocks()) {
        instruction_count += block.instructions.size();
    }
    std::ostringstream stream;
    stream << "General routine with " << function.graph.blocks().size() << " blocks and " << instruction_count
           << " instructions.";
    return stream.str();
}

std::string choose_suggested_name(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings,
    const bool is_entry
) {
    if (!is_autogenerated_name(function.name)) {
        return function.name;
    }
    if (is_entry || std::find(imports.begin(), imports.end(), "__libc_start_main") != imports.end()) {
        return "entry_startup";
    }
    if (std::find(imports.begin(), imports.end(), "nanosleep") != imports.end()) {
        return "sleep_helper";
    }
    if (std::find(imports.begin(), imports.end(), "strlen") != imports.end() &&
        std::find(imports.begin(), imports.end(), "memcmp") != imports.end()) {
        return "string_compare_helper";
    }
    if (!strings.empty()) {
        const std::string base = sanitize_name(strings.front().substr(0, std::min<std::size_t>(24, strings.front().size())));
        if (!base.empty()) {
            return base;
        }
    }
    return function.name;
}

std::vector<std::string> collect_hints(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings,
    const bool is_entry
) {
    std::vector<std::string> hints;
    if (is_entry) {
        hints.push_back("Entry-point context suggests process/bootstrap setup.");
    }
    if (std::find(imports.begin(), imports.end(), "__libc_start_main") != imports.end()) {
        hints.push_back("Calls __libc_start_main, which strongly indicates startup code.");
    }
    if (std::find(imports.begin(), imports.end(), "nanosleep") != imports.end()) {
        hints.push_back("Calls nanosleep, which suggests throttling, retry delay, or loop pacing.");
    }
    if (std::find(imports.begin(), imports.end(), "memcmp") != imports.end()) {
        hints.push_back("Calls memcmp, which suggests byte-sequence comparison logic.");
    }
    if (std::find(imports.begin(), imports.end(), "strlen") != imports.end()) {
        hints.push_back("Calls strlen, which suggests string-oriented processing.");
    }
    if (std::find(imports.begin(), imports.end(), "__stack_chk_fail") != imports.end()) {
        hints.push_back("Contains stack-canary failure path.");
    }
    for (std::size_t index = 0; index < std::min<std::size_t>(strings.size(), 2); ++index) {
        hints.push_back("References string: " + strings[index]);
    }
    if (function.graph.blocks().size() >= 10) {
        hints.push_back("High block count indicates non-trivial control flow.");
    }
    return hints;
}

std::vector<PatternDetection> collect_patterns(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings,
    const bool is_entry
) {
    std::vector<PatternDetection> patterns;
    std::set<std::pair<std::string, std::string>> seen;

    auto add_pattern = [&](std::string category, std::string label, std::string confidence, std::string detail) {
        const auto key = std::make_pair(category, label);
        if (!seen.insert(key).second) {
            return;
        }
        patterns.push_back(
            PatternDetection{
                .category = std::move(category),
                .label = std::move(label),
                .confidence = std::move(confidence),
                .detail = std::move(detail),
            }
        );
    };

    if (is_entry || contains_value(imports, "__libc_start_main")) {
        add_pattern(
            "bootstrap",
            "startup/bootstrap",
            "high",
            "Entry-point context and startup imports indicate process bootstrap logic."
        );
    }
    if (contains_any_import(imports, {"strlen", "strcmp", "strncmp", "memcmp", "strcasecmp"}) ||
        strings_contain_token(strings, {"password", "token", "auth", "credential"})) {
        add_pattern(
            "comparison",
            "authentication or comparison routine",
            "medium",
            "Comparison-style imports or credential-like strings suggest validation logic."
        );
    }
    if (contains_any_import(imports, {"open", "fopen", "read", "write", "close", "stat"})) {
        add_pattern("io", "file I/O", "medium", "File-oriented imports suggest parsing, logging, or file processing behavior.");
    }
    if (contains_any_import(imports, {"socket", "connect", "accept", "send", "recv"}) ||
        strings_contain_token(strings, {"http", "https", "user-agent", "host:", "cookie"})) {
        add_pattern("network", "network I/O", "medium", "Socket imports or protocol strings suggest network-facing behavior.");
    }
    if (contains_any_import(imports, {"system", "popen", "execve", "CreateProcessA", "CreateProcessW"}) ||
        strings_contain_token(strings, {"/bin/sh", "cmd.exe", "powershell"})) {
        add_pattern("execution", "command execution", "high", "Command-launch imports or shell strings indicate process-spawn behavior.");
    }
    if (contains_any_import(imports, {"AES_encrypt", "AES_decrypt", "MD5", "SHA1", "SHA256", "crypt"}) ||
        strings_contain_token(strings, {"aes", "sha", "md5", "crc", "encrypt", "decrypt"})) {
        add_pattern("crypto", "cryptography or checksum", "medium", "Crypto-like imports or strings suggest hashing, checksums, or encryption code.");
    }
    if (!function.graph.loops().empty()) {
        add_pattern(
            "control_flow",
            "loop-heavy processing",
            function.graph.loops().size() > 1 ? "high" : "medium",
            "Recovered loop headers indicate iterative processing."
        );
    }
    if (!function.graph.switches().empty()) {
        add_pattern(
            "control_flow",
            "dispatcher or switch table",
            "high",
            "Recovered switch or jump-table targets indicate a dispatcher-style routine."
        );
    }
    if (function.summary.stack_frame_size >= 0x80) {
        add_pattern(
            "stack",
            "stack-local buffer handling",
            "medium",
            "Recovered stack frame size suggests non-trivial local stack storage."
        );
    }

    return patterns;
}

std::vector<VulnerabilityHint> collect_vulnerability_hints(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings
) {
    std::vector<VulnerabilityHint> hints;
    std::set<std::string> seen;

    auto add_hint = [&](std::string severity, std::string title, std::string detail) {
        const std::string key = severity + "|" + title + "|" + detail;
        if (!seen.insert(key).second) {
            return;
        }
        hints.push_back(
            VulnerabilityHint{
                .severity = std::move(severity),
                .title = std::move(title),
                .detail = std::move(detail),
            }
        );
    };

    if (contains_any_import(imports, {"gets", "strcpy", "strcat", "sprintf", "vsprintf", "scanf", "sscanf", "fscanf"})) {
        add_hint(
            "high",
            "Unsafe stack or string copy surface",
            "Unsafe C library entry points suggest overflow-prone input or string handling."
        );
    }
    if (contains_any_import(imports, {"memcpy", "memmove", "read", "recv"}) && function.summary.stack_frame_size >= 0x40) {
        add_hint(
            "medium",
            "Input reaches sizeable stack frame",
            "Input or copy primitives execute in a function with a recovered local stack frame, which is worth stack-bound review."
        );
    }
    if (contains_any_import(imports, {"printf", "fprintf", "snprintf", "vprintf"}) &&
        strings_contain_token(strings, {"%", "%s", "%x", "%n"})) {
        add_hint(
            "medium",
            "Format-string exposure",
            "Formatting imports plus literal format strings indicate a potential format-string surface."
        );
    }
    if (contains_any_import(imports, {"system", "popen", "execve"}) ||
        strings_contain_token(strings, {"/bin/sh", "cmd.exe", "sh -c"})) {
        add_hint(
            "high",
            "Command execution path",
            "Shell strings or command-execution imports indicate a direct command-launch primitive."
        );
    }
    if (!function.graph.switches().empty() && !function.summary.indirect_resolutions.empty()) {
        add_hint(
            "low",
            "Indirect control flow",
            "Indirect dispatch recovered from the CFG can hide sink selection and deserves control-flow review."
        );
    }

    return hints;
}

FunctionInsight build_heuristic_insight(
    const analysis::DiscoveredFunction& function,
    const std::vector<std::string>& imports,
    const std::vector<std::string>& strings,
    const bool is_entry
) {
    return FunctionInsight{
        .entry_address = function.entry_address,
        .current_name = function.name,
        .suggested_name = choose_suggested_name(function, imports, strings, is_entry),
        .summary = choose_summary(function, imports, strings, is_entry),
        .hints = collect_hints(function, imports, strings, is_entry),
        .patterns = collect_patterns(function, imports, strings, is_entry),
        .vulnerability_hints = collect_vulnerability_hints(function, imports, strings),
    };
}

std::unordered_map<std::uint64_t, std::vector<std::string>> collect_imports_by_function(
    const analysis::ProgramAnalysis& program
) {
    std::unordered_map<std::uint64_t, std::vector<std::string>> imports_by_function;
    for (const auto& edge : program.call_graph) {
        if (!edge.is_import) {
            continue;
        }
        imports_by_function[edge.caller_entry].push_back(normalize_import_name(edge.callee_name));
    }

    for (auto& [_, imports] : imports_by_function) {
        std::sort(imports.begin(), imports.end());
        imports.erase(std::unique(imports.begin(), imports.end()), imports.end());
    }

    return imports_by_function;
}

std::unordered_map<std::uint64_t, std::vector<std::string>> collect_strings_by_function(
    const analysis::ProgramAnalysis& program
) {
    std::unordered_map<std::uint64_t, std::vector<std::string>> strings_by_function;
    for (const auto& function : program.functions) {
        auto& strings = strings_by_function[function.entry_address];
        for (const auto& xref : program.xrefs) {
            if (xref.kind != xrefs::CrossReferenceKind::String) {
                continue;
            }
            if (function_contains_address(function, xref.from_address) && !xref.label.empty()) {
                strings.push_back(xref.label);
            }
        }
        std::sort(strings.begin(), strings.end());
        strings.erase(std::unique(strings.begin(), strings.end()), strings.end());
    }
    return strings_by_function;
}

std::vector<FunctionContext> build_function_contexts(
    const analysis::ProgramAnalysis& program,
    const std::optional<std::uint64_t> entry_point
) {
    const auto imports_by_function = collect_imports_by_function(program);
    const auto strings_by_function = collect_strings_by_function(program);

    std::vector<FunctionContext> contexts;
    contexts.reserve(program.functions.size());

    for (const auto& function : program.functions) {
        FunctionContext context;
        context.function = &function;
        if (const auto imports_it = imports_by_function.find(function.entry_address); imports_it != imports_by_function.end()) {
            context.imports = imports_it->second;
        }
        if (const auto strings_it = strings_by_function.find(function.entry_address); strings_it != strings_by_function.end()) {
            context.strings = strings_it->second;
        }
        context.is_entry = entry_point.has_value() && *entry_point == function.entry_address;

        int score = 0;
        if (context.is_entry) {
            score += 500;
        }
        score += static_cast<int>(context.imports.size()) * 30;
        score += static_cast<int>(context.strings.size()) * 25;
        score += static_cast<int>(function.graph.blocks().size()) * 4;
        score += static_cast<int>(function.summary.arguments.size()) * 10;
        score += static_cast<int>(function.summary.locals.size()) * 6;
        score += static_cast<int>(function.graph.loops().size()) * 12;
        score += static_cast<int>(function.graph.switches().size()) * 20;
        if (!function.summary.indirect_resolutions.empty()) {
            score += 25;
        }
        if (function.summary.stack_frame_size >= 0x40) {
            score += 15;
        }
        context.score = score;
        contexts.push_back(std::move(context));
    }

    return contexts;
}

std::vector<FunctionInsight> build_heuristic_insights(
    const analysis::ProgramAnalysis&,
    const std::vector<FunctionContext>& contexts
) {
    std::vector<FunctionInsight> insights;
    insights.reserve(contexts.size());
    for (const auto& context : contexts) {
        insights.push_back(
            build_heuristic_insight(*context.function, context.imports, context.strings, context.is_entry)
        );
    }
    std::sort(
        insights.begin(),
        insights.end(),
        [](const FunctionInsight& lhs, const FunctionInsight& rhs) { return lhs.entry_address < rhs.entry_address; }
    );
    return insights;
}

std::string first_lines(const std::string& value, const std::size_t max_lines, const std::size_t max_chars) {
    std::istringstream stream(value);
    std::ostringstream output;
    std::string line;
    std::size_t emitted = 0;
    std::size_t chars = 0;
    while (std::getline(stream, line) && emitted < max_lines && chars < max_chars) {
        if (chars + line.size() > max_chars) {
            line = line.substr(0, max_chars - chars);
        }
        if (emitted > 0) {
            output << '\n';
            ++chars;
        }
        output << line;
        chars += line.size();
        ++emitted;
    }
    return output.str();
}

std::string json_escape(const std::string_view value) {
    std::string escaped;
    escaped.reserve(value.size() + 8);
    for (const char character : value) {
        switch (character) {
        case '\\':
            escaped += "\\\\";
            break;
        case '"':
            escaped += "\\\"";
            break;
        case '\n':
            escaped += "\\n";
            break;
        case '\r':
            escaped += "\\r";
            break;
        case '\t':
            escaped += "\\t";
            break;
        default:
            escaped.push_back(character);
            break;
        }
    }
    return escaped;
}

std::string json_string(const std::string_view value) {
    return "\"" + json_escape(value) + "\"";
}

std::string format_address(const std::uint64_t address) {
    std::ostringstream stream;
    stream << "0x" << std::uppercase << std::hex << address;
    return stream.str();
}

std::string join(const std::vector<std::string>& values) {
    std::ostringstream stream;
    for (std::size_t index = 0; index < values.size(); ++index) {
        if (index > 0) {
            stream << ", ";
        }
        stream << values[index];
    }
    return stream.str();
}

std::string build_function_model_context(const FunctionContext& context) {
    const auto& function = *context.function;
    std::ostringstream stream;
    stream << "entry=" << format_address(function.entry_address) << '\n';
    stream << "name=" << function.name << '\n';
    stream << "section=" << function.section_name << '\n';
    stream << "blocks=" << function.graph.blocks().size() << '\n';

    std::size_t instruction_count = 0;
    for (const auto& block : function.graph.blocks()) {
        instruction_count += block.instructions.size();
    }
    stream << "instructions=" << instruction_count << '\n';
    stream << "calling_convention=" << analysis::to_string(function.summary.calling_convention) << '\n';
    stream << "stack_frame_size=" << function.summary.stack_frame_size << '\n';
    stream << "loops=" << function.graph.loops().size() << '\n';
    stream << "switches=" << function.graph.switches().size() << '\n';
    stream << "imports=" << (context.imports.empty() ? "-" : first_lines(join(context.imports), 1, 256)) << '\n';
    stream << "strings=" << (context.strings.empty() ? "-" : first_lines(join(context.strings), 3, 256)) << '\n';
    stream << "locals=" << function.summary.locals.size() << '\n';
    stream << "arguments=" << function.summary.arguments.size() << '\n';
    stream << "indirect_targets=" << function.summary.indirect_resolutions.size() << '\n';
    const std::string pseudocode_preview = first_lines(function.decompiled.pseudocode, 10, 900);
    if (!pseudocode_preview.empty()) {
        stream << "pseudocode:\n" << pseudocode_preview << '\n';
    }
    return stream.str();
}

std::vector<FunctionContext> select_model_candidates(
    std::vector<FunctionContext> contexts,
    const std::size_t max_functions
) {
    std::sort(
        contexts.begin(),
        contexts.end(),
        [](const FunctionContext& left, const FunctionContext& right) {
            return std::pair(-left.score, left.function->entry_address) < std::pair(-right.score, right.function->entry_address);
        }
    );
    if (contexts.size() > max_functions) {
        contexts.resize(max_functions);
    }
    std::sort(
        contexts.begin(),
        contexts.end(),
        [](const FunctionContext& left, const FunctionContext& right) {
            return left.function->entry_address < right.function->entry_address;
        }
    );
    return contexts;
}

std::string build_model_output_contract() {
    return
        "Return exactly one JSON object with this shape:\n"
        "{\n"
        "  \"functions\": [\n"
        "    {\n"
        "      \"entry_address\": \"0x401000\",\n"
        "      \"suggested_name\": \"name_or_existing_name\",\n"
        "      \"summary\": \"short factual summary\",\n"
        "      \"hints\": [\"short hint\"],\n"
        "      \"patterns\": [\n"
        "        {\n"
        "          \"category\": \"category\",\n"
        "          \"label\": \"label\",\n"
        "          \"confidence\": \"low|medium|high\",\n"
        "          \"detail\": \"short factual detail\"\n"
        "        }\n"
        "      ],\n"
        "      \"vulnerability_hints\": [\n"
        "        {\n"
        "          \"severity\": \"low|medium|high|critical\",\n"
        "          \"title\": \"title\",\n"
        "          \"detail\": \"short factual detail\"\n"
        "        }\n"
        "      ]\n"
        "    }\n"
        "  ]\n"
        "}\n"
        "Do not wrap the JSON in markdown fences. Do not include commentary before or after the JSON.\n";
}

std::string build_model_prompt(const std::vector<FunctionContext>& contexts) {
    std::ostringstream payload;
    payload << "You are assisting a reverse engineering platform.\n"
            << "Analyze recovered binary functions and return concise analyst-grade rename, summary, pattern, and vulnerability hints.\n"
            << "Use the current function name when you are not confident in a better rename.\n"
            << "Keep summaries short and factual.\n"
            << "Do not invent imports, strings, or vulnerabilities that are not supported by the context.\n\n"
            << build_model_output_contract() << '\n';

    for (std::size_t index = 0; index < contexts.size(); ++index) {
        if (index > 0) {
            payload << "\n---\n";
        }
        payload << build_function_model_context(contexts[index]);
    }

    return payload.str();
}

std::string build_openai_request_json(
    const std::vector<FunctionContext>& contexts,
    const OpenAIOptions& options
) {
    const std::string prompt = build_model_prompt(contexts);

    std::ostringstream request;
    request << '{'
            << "\"model\":" << json_string(options.model) << ','
            << "\"input\":["
            << "{\"role\":\"system\",\"content\":[{\"type\":\"input_text\",\"text\":"
            << json_string("Analyze recovered binary functions and return structured rename/summary/pattern/vulnerability hints.") << "}]},"
            << "{\"role\":\"user\",\"content\":[{\"type\":\"input_text\",\"text\":" << json_string(prompt) << "}]}"
            << "],"
            << "\"text\":{\"format\":{"
            << "\"type\":\"json_schema\","
            << "\"name\":\"zara_function_insights\","
            << "\"strict\":true,"
            << "\"schema\":{"
            << "\"type\":\"object\","
            << "\"additionalProperties\":false,"
            << "\"properties\":{"
            << "\"functions\":{"
            << "\"type\":\"array\","
            << "\"items\":{"
            << "\"type\":\"object\","
            << "\"additionalProperties\":false,"
            << "\"properties\":{"
            << "\"entry_address\":{\"type\":\"string\"},"
            << "\"suggested_name\":{\"type\":\"string\"},"
            << "\"summary\":{\"type\":\"string\"},"
            << "\"hints\":{\"type\":\"array\",\"items\":{\"type\":\"string\"}},"
            << "\"patterns\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{"
            << "\"category\":{\"type\":\"string\"},"
            << "\"label\":{\"type\":\"string\"},"
            << "\"confidence\":{\"type\":\"string\"},"
            << "\"detail\":{\"type\":\"string\"}"
            << "},\"required\":[\"category\",\"label\",\"confidence\",\"detail\"]}},"
            << "\"vulnerability_hints\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"properties\":{"
            << "\"severity\":{\"type\":\"string\"},"
            << "\"title\":{\"type\":\"string\"},"
            << "\"detail\":{\"type\":\"string\"}"
            << "},\"required\":[\"severity\",\"title\",\"detail\"]}}"
            << "},\"required\":[\"entry_address\",\"suggested_name\",\"summary\",\"hints\",\"patterns\",\"vulnerability_hints\"]}"
            << "}"
            << "},\"required\":[\"functions\"]"
            << "}}}";
    return request.str();
}

std::string build_anthropic_request_json(
    const std::vector<FunctionContext>& contexts,
    const AnthropicOptions& options
) {
    const std::string prompt = build_model_prompt(contexts);
    std::ostringstream request;
    request << '{'
            << "\"model\":" << json_string(options.model) << ','
            << "\"max_tokens\":4096,"
            << "\"system\":" << json_string("Return JSON only. Do not include markdown fences.") << ','
            << "\"messages\":[{\"role\":\"user\",\"content\":[{\"type\":\"text\",\"text\":" << json_string(prompt) << "}]}]"
            << '}';
    return request.str();
}

std::string build_gemini_request_json(
    const std::vector<FunctionContext>& contexts,
    const GeminiOptions& options
) {
    const std::string prompt = build_model_prompt(contexts);
    std::ostringstream request;
    request << '{'
            << "\"contents\":[{\"role\":\"user\",\"parts\":[{\"text\":" << json_string(prompt) << "}]}],"
            << "\"generationConfig\":{"
            << "\"temperature\":0.1,"
            << "\"responseMimeType\":\"application/json\""
            << "}"
            << '}';
    return request.str();
}

std::string build_compatible_request_json(
    const std::vector<FunctionContext>& contexts,
    const CompatibleModelOptions& options
) {
    const std::string prompt = build_model_prompt(contexts);
    std::ostringstream request;
    request << '{'
            << "\"model\":" << json_string(options.model) << ','
            << "\"temperature\":0.1,"
            << "\"messages\":["
            << "{\"role\":\"system\",\"content\":"
            << json_string("Return exactly one JSON object and no surrounding commentary or markdown.") << "},"
            << "{\"role\":\"user\",\"content\":" << json_string(prompt) << "}"
            << "]"
            << '}';
    return request.str();
}

std::size_t skip_whitespace(const std::string_view text, std::size_t position) {
    while (position < text.size() && std::isspace(static_cast<unsigned char>(text[position])) != 0) {
        ++position;
    }
    return position;
}

std::optional<std::size_t> find_field_value_start(const std::string_view json, const std::string_view field) {
    const std::string key = "\"" + std::string(field) + "\"";
    const auto key_position = json.find(key);
    if (key_position == std::string_view::npos) {
        return std::nullopt;
    }
    const auto colon_position = json.find(':', key_position + key.size());
    if (colon_position == std::string_view::npos) {
        return std::nullopt;
    }
    return skip_whitespace(json, colon_position + 1);
}

std::optional<std::size_t> find_matching_delimiter(
    const std::string_view text,
    const std::size_t open_position,
    const char open_char,
    const char close_char
) {
    int depth = 0;
    bool in_string = false;
    bool escaped = false;
    for (std::size_t index = open_position; index < text.size(); ++index) {
        const char character = text[index];
        if (escaped) {
            escaped = false;
            continue;
        }
        if (character == '\\') {
            escaped = true;
            continue;
        }
        if (character == '"') {
            in_string = !in_string;
            continue;
        }
        if (in_string) {
            continue;
        }
        if (character == open_char) {
            ++depth;
        } else if (character == close_char) {
            --depth;
            if (depth == 0) {
                return index;
            }
        }
    }
    return std::nullopt;
}

std::string json_unescape(const std::string_view value) {
    std::string output;
    output.reserve(value.size());

    bool escaped = false;
    for (std::size_t index = 0; index < value.size(); ++index) {
        const char character = value[index];
        if (!escaped) {
            if (character == '\\') {
                escaped = true;
                continue;
            }
            output.push_back(character);
            continue;
        }

        escaped = false;
        switch (character) {
        case '\\':
            output.push_back('\\');
            break;
        case '"':
            output.push_back('"');
            break;
        case 'n':
            output.push_back('\n');
            break;
        case 'r':
            output.push_back('\r');
            break;
        case 't':
            output.push_back('\t');
            break;
        case 'u':
            if (index + 4 < value.size()) {
                index += 4;
            }
            break;
        default:
            output.push_back(character);
            break;
        }
    }
    return output;
}

std::optional<std::string> extract_json_string_value(const std::string_view json, const std::string_view field) {
    const auto value_position = find_field_value_start(json, field);
    if (!value_position.has_value() || *value_position >= json.size() || json[*value_position] != '"') {
        return std::nullopt;
    }

    bool escaped = false;
    for (std::size_t index = *value_position + 1; index < json.size(); ++index) {
        const char character = json[index];
        if (escaped) {
            escaped = false;
            continue;
        }
        if (character == '\\') {
            escaped = true;
            continue;
        }
        if (character == '"') {
            return json_unescape(json.substr(*value_position + 1, index - *value_position - 1));
        }
    }

    return std::nullopt;
}

std::vector<std::string> extract_json_string_array(const std::string_view json, const std::string_view field) {
    const auto value_position = find_field_value_start(json, field);
    if (!value_position.has_value() || *value_position >= json.size() || json[*value_position] != '[') {
        return {};
    }

    const auto close_position = find_matching_delimiter(json, *value_position, '[', ']');
    if (!close_position.has_value()) {
        return {};
    }

    std::vector<std::string> values;
    std::size_t cursor = *value_position + 1;
    while (cursor < *close_position) {
        cursor = skip_whitespace(json, cursor);
        if (cursor >= *close_position) {
            break;
        }
        if (json[cursor] != '"') {
            ++cursor;
            continue;
        }

        bool escaped = false;
        std::size_t end = cursor + 1;
        for (; end < *close_position; ++end) {
            const char character = json[end];
            if (escaped) {
                escaped = false;
                continue;
            }
            if (character == '\\') {
                escaped = true;
                continue;
            }
            if (character == '"') {
                break;
            }
        }
        if (end >= *close_position) {
            break;
        }
        values.push_back(json_unescape(json.substr(cursor + 1, end - cursor - 1)));
        cursor = end + 1;
    }
    return values;
}

std::vector<std::string> extract_json_object_array(const std::string_view json, const std::string_view field) {
    const auto value_position = find_field_value_start(json, field);
    if (!value_position.has_value() || *value_position >= json.size() || json[*value_position] != '[') {
        return {};
    }

    const auto close_position = find_matching_delimiter(json, *value_position, '[', ']');
    if (!close_position.has_value()) {
        return {};
    }

    std::vector<std::string> values;
    std::size_t cursor = *value_position + 1;
    while (cursor < *close_position) {
        cursor = skip_whitespace(json, cursor);
        if (cursor >= *close_position) {
            break;
        }
        if (json[cursor] != '{') {
            ++cursor;
            continue;
        }

        const auto object_end = find_matching_delimiter(json, cursor, '{', '}');
        if (!object_end.has_value() || *object_end > *close_position) {
            break;
        }
        values.emplace_back(json.substr(cursor, *object_end - cursor + 1));
        cursor = *object_end + 1;
    }
    return values;
}

std::optional<std::uint64_t> parse_address_string(const std::string_view text) {
    if (text.empty()) {
        return std::nullopt;
    }

    try {
        std::size_t consumed = 0;
        const int base = text.starts_with("0x") || text.starts_with("0X") ? 16 : 10;
        const auto value = std::stoull(std::string(text), &consumed, base);
        if (consumed != text.size()) {
            return std::nullopt;
        }
        return static_cast<std::uint64_t>(value);
    } catch (...) {
        return std::nullopt;
    }
}

std::vector<ModelFunctionInsight> parse_model_function_insights(const std::string& output_text) {
    std::vector<ModelFunctionInsight> parsed;
    for (const auto& object : extract_json_object_array(output_text, "functions")) {
        const auto entry_address = extract_json_string_value(object, "entry_address");
        const auto parsed_entry = entry_address.has_value() ? parse_address_string(*entry_address) : std::nullopt;
        if (!parsed_entry.has_value()) {
            continue;
        }

        ModelFunctionInsight insight;
        insight.entry_address = *parsed_entry;
        insight.suggested_name = extract_json_string_value(object, "suggested_name").value_or("");
        insight.summary = extract_json_string_value(object, "summary").value_or("");
        insight.hints = extract_json_string_array(object, "hints");

        for (const auto& pattern_object : extract_json_object_array(object, "patterns")) {
            insight.patterns.push_back(
                PatternDetection{
                    .category = extract_json_string_value(pattern_object, "category").value_or(""),
                    .label = extract_json_string_value(pattern_object, "label").value_or(""),
                    .confidence = extract_json_string_value(pattern_object, "confidence").value_or(""),
                    .detail = extract_json_string_value(pattern_object, "detail").value_or(""),
                }
            );
        }

        for (const auto& hint_object : extract_json_object_array(object, "vulnerability_hints")) {
            insight.vulnerability_hints.push_back(
                VulnerabilityHint{
                    .severity = extract_json_string_value(hint_object, "severity").value_or(""),
                    .title = extract_json_string_value(hint_object, "title").value_or(""),
                    .detail = extract_json_string_value(hint_object, "detail").value_or(""),
                }
            );
        }

        parsed.push_back(std::move(insight));
    }

    return parsed;
}

std::optional<std::string> parse_openai_output_text(const std::string& response_json) {
    const auto output_text = extract_json_string_value(response_json, "output_text");
    if (!output_text.has_value()) {
        return std::nullopt;
    }

    const auto first_non_space = output_text->find_first_not_of(" \t\r\n");
    const auto last_non_space = output_text->find_last_not_of(" \t\r\n");
    if (first_non_space == std::string::npos || last_non_space == std::string::npos) {
        return std::nullopt;
    }
    if ((*output_text)[first_non_space] != '{' || (*output_text)[last_non_space] != '}') {
        return std::nullopt;
    }
    return output_text;
}

std::optional<std::string> normalize_json_output_text(std::string text) {
    const auto first_non_space = text.find_first_not_of(" \t\r\n");
    if (first_non_space == std::string::npos) {
        return std::nullopt;
    }
    text.erase(0, first_non_space);

    if (text.rfind("```", 0) == 0) {
        const auto first_newline = text.find('\n');
        if (first_newline == std::string::npos) {
            return std::nullopt;
        }
        text.erase(0, first_newline + 1);
        const auto fence_end = text.rfind("```");
        if (fence_end != std::string::npos) {
            text.erase(fence_end);
        }
    }

    const auto object_start = text.find('{');
    if (object_start == std::string::npos) {
        return std::nullopt;
    }
    const auto object_end = find_matching_delimiter(text, object_start, '{', '}');
    if (!object_end.has_value()) {
        return std::nullopt;
    }
    return text.substr(object_start, *object_end - object_start + 1);
}

std::optional<std::string> parse_anthropic_output_text(const std::string& response_json) {
    const auto text = extract_json_string_value(response_json, "text");
    if (!text.has_value()) {
        return std::nullopt;
    }
    return normalize_json_output_text(*text);
}

std::optional<std::string> parse_gemini_output_text(const std::string& response_json) {
    const auto text = extract_json_string_value(response_json, "text");
    if (!text.has_value()) {
        return std::nullopt;
    }
    return normalize_json_output_text(*text);
}

std::optional<std::string> parse_compatible_output_text(const std::string& response_json) {
    if (const auto content = extract_json_string_value(response_json, "content"); content.has_value()) {
        if (const auto normalized = normalize_json_output_text(*content); normalized.has_value()) {
            return normalized;
        }
    }
    if (const auto text = extract_json_string_value(response_json, "text"); text.has_value()) {
        return normalize_json_output_text(*text);
    }
    return std::nullopt;
}

std::optional<std::string> environment_string(const char* name) {
    if (const char* value = std::getenv(name); value != nullptr && *value != '\0') {
        return std::string(value);
    }
    return std::nullopt;
}

std::optional<std::size_t> environment_size(const char* name) {
    const auto value = environment_string(name);
    if (!value.has_value()) {
        return std::nullopt;
    }

    try {
        return static_cast<std::size_t>(std::stoull(*value));
    } catch (...) {
        return std::nullopt;
    }
}

std::optional<long> environment_long(const char* name) {
    const auto value = environment_string(name);
    if (!value.has_value()) {
        return std::nullopt;
    }

    try {
        return std::stol(*value);
    } catch (...) {
        return std::nullopt;
    }
}

std::optional<OpenAIOptions> resolve_openai_options(const AssistantOptions& options) {
    if (options.backend != AssistantBackend::OpenAI && options.backend != AssistantBackend::Auto) {
        return std::nullopt;
    }

    OpenAIOptions resolved;
    if (options.openai.has_value()) {
        resolved = *options.openai;
    }

    if (resolved.api_key.empty()) {
        const auto api_key = environment_string("ZARA_OPENAI_API_KEY");
        if (api_key.has_value()) {
            resolved.api_key = *api_key;
        }
    }
    if (resolved.model.empty()) {
        if (const auto model = environment_string("ZARA_OPENAI_MODEL"); model.has_value()) {
            resolved.model = *model;
        }
    }
    if (resolved.base_url.empty()) {
        if (const auto base_url = environment_string("ZARA_OPENAI_BASE_URL"); base_url.has_value()) {
            resolved.base_url = *base_url;
        }
    }
    if (resolved.organization.empty()) {
        if (const auto organization = environment_string("ZARA_OPENAI_ORGANIZATION"); organization.has_value()) {
            resolved.organization = *organization;
        }
    }
    if (resolved.project.empty()) {
        if (const auto project = environment_string("ZARA_OPENAI_PROJECT"); project.has_value()) {
            resolved.project = *project;
        }
    }
    if (resolved.max_functions == 0) {
        if (const auto max_functions = environment_size("ZARA_OPENAI_MAX_FUNCTIONS"); max_functions.has_value()) {
            resolved.max_functions = *max_functions;
        }
    }
    if (resolved.timeout_ms <= 0) {
        if (const auto timeout = environment_long("ZARA_OPENAI_TIMEOUT_MS"); timeout.has_value()) {
            resolved.timeout_ms = *timeout;
        }
    }

    if (resolved.api_key.empty()) {
        return std::nullopt;
    }
    return resolved;
}

std::optional<AnthropicOptions> resolve_anthropic_options(const AssistantOptions& options) {
    if (options.backend != AssistantBackend::Anthropic) {
        return std::nullopt;
    }

    AnthropicOptions resolved;
    if (options.anthropic.has_value()) {
        resolved = *options.anthropic;
    }
    if (resolved.api_key.empty()) {
        if (const auto api_key = environment_string("ZARA_ANTHROPIC_API_KEY"); api_key.has_value()) {
            resolved.api_key = *api_key;
        }
    }
    if (resolved.model.empty()) {
        if (const auto model = environment_string("ZARA_ANTHROPIC_MODEL"); model.has_value()) {
            resolved.model = *model;
        }
    }
    if (resolved.base_url.empty()) {
        if (const auto base_url = environment_string("ZARA_ANTHROPIC_BASE_URL"); base_url.has_value()) {
            resolved.base_url = *base_url;
        }
    }
    if (resolved.max_functions == 0) {
        if (const auto max_functions = environment_size("ZARA_ANTHROPIC_MAX_FUNCTIONS"); max_functions.has_value()) {
            resolved.max_functions = *max_functions;
        }
    }
    if (resolved.timeout_ms <= 0) {
        if (const auto timeout = environment_long("ZARA_ANTHROPIC_TIMEOUT_MS"); timeout.has_value()) {
            resolved.timeout_ms = *timeout;
        }
    }
    if (resolved.api_version.empty()) {
        if (const auto api_version = environment_string("ZARA_ANTHROPIC_API_VERSION"); api_version.has_value()) {
            resolved.api_version = *api_version;
        }
    }

    if (resolved.api_key.empty() || resolved.model.empty()) {
        return std::nullopt;
    }
    return resolved;
}

std::optional<GeminiOptions> resolve_gemini_options(const AssistantOptions& options) {
    if (options.backend != AssistantBackend::Gemini) {
        return std::nullopt;
    }

    GeminiOptions resolved;
    if (options.gemini.has_value()) {
        resolved = *options.gemini;
    }
    if (resolved.api_key.empty()) {
        if (const auto api_key = environment_string("ZARA_GEMINI_API_KEY"); api_key.has_value()) {
            resolved.api_key = *api_key;
        }
    }
    if (resolved.model.empty()) {
        if (const auto model = environment_string("ZARA_GEMINI_MODEL"); model.has_value()) {
            resolved.model = *model;
        }
    }
    if (resolved.base_url.empty()) {
        if (const auto base_url = environment_string("ZARA_GEMINI_BASE_URL"); base_url.has_value()) {
            resolved.base_url = *base_url;
        }
    }
    if (resolved.max_functions == 0) {
        if (const auto max_functions = environment_size("ZARA_GEMINI_MAX_FUNCTIONS"); max_functions.has_value()) {
            resolved.max_functions = *max_functions;
        }
    }
    if (resolved.timeout_ms <= 0) {
        if (const auto timeout = environment_long("ZARA_GEMINI_TIMEOUT_MS"); timeout.has_value()) {
            resolved.timeout_ms = *timeout;
        }
    }

    if (resolved.api_key.empty() || resolved.model.empty()) {
        return std::nullopt;
    }
    return resolved;
}

std::optional<CompatibleModelOptions> resolve_compatible_options(const AssistantOptions& options) {
    if (options.backend != AssistantBackend::OpenAICompatible && options.backend != AssistantBackend::LocalLLM) {
        return std::nullopt;
    }

    CompatibleModelOptions resolved;
    if (options.compatible.has_value()) {
        resolved = *options.compatible;
    }

    const char* api_key_var = options.backend == AssistantBackend::LocalLLM ? "ZARA_LOCAL_LLM_API_KEY"
                                                                            : "ZARA_COMPATIBLE_API_KEY";
    const char* model_var = options.backend == AssistantBackend::LocalLLM ? "ZARA_LOCAL_LLM_MODEL"
                                                                          : "ZARA_COMPATIBLE_MODEL";
    const char* base_url_var = options.backend == AssistantBackend::LocalLLM ? "ZARA_LOCAL_LLM_BASE_URL"
                                                                             : "ZARA_COMPATIBLE_BASE_URL";
    const char* max_functions_var =
        options.backend == AssistantBackend::LocalLLM ? "ZARA_LOCAL_LLM_MAX_FUNCTIONS" : "ZARA_COMPATIBLE_MAX_FUNCTIONS";
    const char* timeout_var =
        options.backend == AssistantBackend::LocalLLM ? "ZARA_LOCAL_LLM_TIMEOUT_MS" : "ZARA_COMPATIBLE_TIMEOUT_MS";

    if (resolved.api_key.empty()) {
        if (const auto api_key = environment_string(api_key_var); api_key.has_value()) {
            resolved.api_key = *api_key;
        }
    }
    if (resolved.model.empty()) {
        if (const auto model = environment_string(model_var); model.has_value()) {
            resolved.model = *model;
        }
    }
    if (resolved.base_url.empty()) {
        if (const auto base_url = environment_string(base_url_var); base_url.has_value()) {
            resolved.base_url = *base_url;
        }
    }
    if (resolved.max_functions == 0) {
        if (const auto max_functions = environment_size(max_functions_var); max_functions.has_value()) {
            resolved.max_functions = *max_functions;
        }
    }
    if (resolved.timeout_ms <= 0) {
        if (const auto timeout = environment_long(timeout_var); timeout.has_value()) {
            resolved.timeout_ms = *timeout;
        }
    }

    if (resolved.model.empty() || resolved.base_url.empty()) {
        return std::nullopt;
    }
    if (options.backend == AssistantBackend::OpenAICompatible && resolved.api_key.empty()) {
        return std::nullopt;
    }
    return resolved;
}

std::string credential_fingerprint(std::string_view secret) {
    if (secret.empty()) {
        return {};
    }

    std::uint64_t hash = 1469598103934665603ULL;
    for (const unsigned char character : secret) {
        hash ^= static_cast<std::uint64_t>(character);
        hash *= 1099511628211ULL;
    }
    std::ostringstream stream;
    stream << "fp-" << std::hex << std::nouppercase << hash;
    return stream.str();
}

std::vector<FunctionInsight> merge_model_insights(
    std::vector<FunctionInsight> insights,
    const std::vector<ModelFunctionInsight>& model_insights
) {
    std::unordered_map<std::uint64_t, ModelFunctionInsight> by_address;
    for (const auto& insight : model_insights) {
        by_address[insight.entry_address] = insight;
    }

    for (auto& insight : insights) {
        const auto it = by_address.find(insight.entry_address);
        if (it == by_address.end()) {
            continue;
        }

        const auto& model = it->second;
        if (!model.suggested_name.empty()) {
            insight.suggested_name = model.suggested_name;
        }
        if (!model.summary.empty()) {
            insight.summary = model.summary;
        }
        insight.hints = model.hints;
        insight.patterns = model.patterns;
        insight.vulnerability_hints = model.vulnerability_hints;
    }

    return insights;
}

#if defined(ZARA_HAS_CURL)
std::size_t curl_write_callback(char* data, const std::size_t size, const std::size_t nmemb, void* user_data) {
    auto* output = static_cast<std::string*>(user_data);
    output->append(data, size * nmemb);
    return size * nmemb;
}

class CurlModelTransport final : public ModelTransport {
public:
    [[nodiscard]] bool create_response(
        const std::string& request_json,
        const AssistantOptions& options,
        std::string& out_response_json,
        std::string& out_error
    ) override {
        out_error.clear();
        out_response_json.clear();

        CURL* curl = curl_easy_init();
        if (curl == nullptr) {
            out_error = "libcurl initialization failed.";
            return false;
        }

        struct curl_slist* headers = nullptr;
        headers = curl_slist_append(headers, "Content-Type: application/json");
        std::string request_url;

        if (const auto openai = resolve_openai_options(options); openai.has_value()) {
            request_url = openai->base_url;
            headers = curl_slist_append(headers, ("Authorization: Bearer " + openai->api_key).c_str());
            if (!openai->organization.empty()) {
                headers = curl_slist_append(headers, ("OpenAI-Organization: " + openai->organization).c_str());
            }
            if (!openai->project.empty()) {
                headers = curl_slist_append(headers, ("OpenAI-Project: " + openai->project).c_str());
            }
            curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, openai->timeout_ms);
        } else if (const auto anthropic = resolve_anthropic_options(options); anthropic.has_value()) {
            request_url = anthropic->base_url;
            headers = curl_slist_append(headers, ("x-api-key: " + anthropic->api_key).c_str());
            headers = curl_slist_append(headers, ("anthropic-version: " + anthropic->api_version).c_str());
            curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, anthropic->timeout_ms);
        } else if (const auto gemini = resolve_gemini_options(options); gemini.has_value()) {
            request_url = gemini->base_url;
            if (!request_url.empty() && request_url.back() != '/') {
                request_url.push_back('/');
            }
            request_url += gemini->model;
            request_url += ":generateContent?key=" + gemini->api_key;
            curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, gemini->timeout_ms);
        } else if (const auto compatible = resolve_compatible_options(options); compatible.has_value()) {
            request_url = compatible->base_url;
            if (!compatible->api_key.empty()) {
                headers = curl_slist_append(headers, ("Authorization: Bearer " + compatible->api_key).c_str());
            }
            curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, compatible->timeout_ms);
        } else {
            curl_slist_free_all(headers);
            curl_easy_cleanup(curl);
            out_error = "Model-backed AI configuration is incomplete.";
            return false;
        }

        curl_easy_setopt(curl, CURLOPT_URL, request_url.c_str());
        curl_easy_setopt(curl, CURLOPT_POST, 1L);
        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(curl, CURLOPT_POSTFIELDS, request_json.c_str());
        curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, static_cast<long>(request_json.size()));
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, &curl_write_callback);
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, &out_response_json);

        const CURLcode result = curl_easy_perform(curl);
        long http_status = 0;
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_status);

        curl_slist_free_all(headers);
        curl_easy_cleanup(curl);

        if (result != CURLE_OK) {
            out_error = std::string("Model request failed: ") + curl_easy_strerror(result);
            return false;
        }
        if (http_status < 200 || http_status >= 300) {
            out_error = "Model request returned HTTP " + std::to_string(http_status) + ".";
            if (const auto error_message = extract_json_string_value(out_response_json, "message"); error_message.has_value()) {
                out_error += " " + *error_message;
            }
            return false;
        }

        return true;
    }
};
#endif

}  // namespace

std::vector<FunctionInsight> Assistant::analyze_program(
    const analysis::ProgramAnalysis& program,
    const std::optional<std::uint64_t> entry_point
) {
    return analyze_program(program, entry_point, AssistantOptions{});
}

std::vector<FunctionInsight> Assistant::analyze_program(
    const analysis::ProgramAnalysis& program,
    const std::optional<std::uint64_t> entry_point,
    const AssistantOptions& options,
    AssistantRunMetadata* out_metadata,
    ModelTransport* transport
) {
    if (out_metadata != nullptr) {
        *out_metadata = {};
    }

    const auto contexts = build_function_contexts(program, entry_point);
    auto insights = build_heuristic_insights(program, contexts);

    const auto openai = resolve_openai_options(options);
    const auto anthropic = resolve_anthropic_options(options);
    const auto gemini = resolve_gemini_options(options);
    const auto compatible = resolve_compatible_options(options);
    if (!openai.has_value() && !anthropic.has_value() && !gemini.has_value() && !compatible.has_value()) {
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            if (options.backend != AssistantBackend::Heuristic && options.backend != AssistantBackend::Auto) {
                out_metadata->warnings.push_back("Configured AI provider is missing required credentials or model settings.");
            }
        }
        return insights;
    }

    std::size_t max_functions = 12;
    if (openai.has_value()) {
        max_functions = openai->max_functions;
    } else if (anthropic.has_value()) {
        max_functions = anthropic->max_functions;
    } else if (gemini.has_value()) {
        max_functions = gemini->max_functions;
    } else if (compatible.has_value()) {
        max_functions = compatible->max_functions;
    }

    auto candidates = select_model_candidates(contexts, std::max<std::size_t>(1, max_functions));
    if (candidates.empty()) {
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            out_metadata->warnings.push_back("No functions were available for model-backed analysis.");
        }
        return insights;
    }

    std::unique_ptr<ModelTransport> owned_transport;
    if (transport == nullptr) {
#if defined(ZARA_HAS_CURL)
        owned_transport = std::make_unique<CurlModelTransport>();
        transport = owned_transport.get();
#else
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            out_metadata->warnings.push_back("Model-backed AI was requested, but libcurl support is not available in this build.");
        }
        return insights;
#endif
    }

    std::string response_json;
    std::string error;
    std::string request_json;
    std::optional<std::string> output_text;
    if (openai.has_value()) {
        request_json = build_openai_request_json(candidates, *openai);
    } else if (anthropic.has_value()) {
        request_json = build_anthropic_request_json(candidates, *anthropic);
    } else if (gemini.has_value()) {
        request_json = build_gemini_request_json(candidates, *gemini);
    } else if (compatible.has_value()) {
        request_json = build_compatible_request_json(candidates, *compatible);
    }
    if (!transport->create_response(request_json, options, response_json, error)) {
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            out_metadata->warnings.push_back(error.empty() ? "The model-backed AI request failed." : error);
        }
        return insights;
    }

    if (openai.has_value()) {
        output_text = parse_openai_output_text(response_json);
    } else if (anthropic.has_value()) {
        output_text = parse_anthropic_output_text(response_json);
    } else if (gemini.has_value()) {
        output_text = parse_gemini_output_text(response_json);
    } else if (compatible.has_value()) {
        output_text = parse_compatible_output_text(response_json);
    }
    if (!output_text.has_value()) {
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            out_metadata->warnings.push_back("The model response did not contain parseable JSON output.");
        }
        return insights;
    }

    const auto parsed = parse_model_function_insights(*output_text);
    if (parsed.empty()) {
        if (out_metadata != nullptr) {
            out_metadata->backend = "heuristic";
            out_metadata->warnings.push_back("The model response could not be parsed into Zara AI insight records.");
        }
        return insights;
    }

    if (out_metadata != nullptr) {
        if (openai.has_value()) {
            out_metadata->backend = "openai";
            out_metadata->model = openai->model;
            out_metadata->credential_fingerprint = credential_fingerprint(openai->api_key);
        } else if (anthropic.has_value()) {
            out_metadata->backend = "anthropic";
            out_metadata->model = anthropic->model;
            out_metadata->credential_fingerprint = credential_fingerprint(anthropic->api_key);
        } else if (gemini.has_value()) {
            out_metadata->backend = "gemini";
            out_metadata->model = gemini->model;
            out_metadata->credential_fingerprint = credential_fingerprint(gemini->api_key);
        } else if (compatible.has_value()) {
            out_metadata->backend = options.backend == AssistantBackend::LocalLLM ? "local_llm" : "openai_compatible";
            out_metadata->model = compatible->model;
            out_metadata->credential_fingerprint = credential_fingerprint(compatible->api_key);
        }
        out_metadata->used_remote_model = options.backend != AssistantBackend::LocalLLM;
    }
    return merge_model_insights(std::move(insights), parsed);
}

AssistantOptions Assistant::options_from_environment() {
    AssistantOptions options;
    if (const auto backend = environment_string("ZARA_AI_BACKEND"); backend.has_value()) {
        if (*backend == "openai") {
            options.backend = AssistantBackend::OpenAI;
        } else if (*backend == "anthropic") {
            options.backend = AssistantBackend::Anthropic;
        } else if (*backend == "gemini") {
            options.backend = AssistantBackend::Gemini;
        } else if (*backend == "openai_compatible") {
            options.backend = AssistantBackend::OpenAICompatible;
        } else if (*backend == "local_llm") {
            options.backend = AssistantBackend::LocalLLM;
        } else if (*backend == "auto") {
            options.backend = AssistantBackend::Auto;
        } else {
            options.backend = AssistantBackend::Heuristic;
        }
    } else if (environment_string("ZARA_OPENAI_API_KEY").has_value()) {
        options.backend = AssistantBackend::Auto;
    } else if (environment_string("ZARA_ANTHROPIC_API_KEY").has_value()) {
        options.backend = AssistantBackend::Anthropic;
    } else if (environment_string("ZARA_GEMINI_API_KEY").has_value()) {
        options.backend = AssistantBackend::Gemini;
    } else if (environment_string("ZARA_COMPATIBLE_MODEL").has_value() || environment_string("ZARA_COMPATIBLE_BASE_URL").has_value()) {
        options.backend = AssistantBackend::OpenAICompatible;
    } else if (environment_string("ZARA_LOCAL_LLM_MODEL").has_value() || environment_string("ZARA_LOCAL_LLM_BASE_URL").has_value()) {
        options.backend = AssistantBackend::LocalLLM;
    }

    if (const auto resolved = resolve_openai_options(options); resolved.has_value()) {
        options.openai = *resolved;
        options.openai->api_key.clear();
    }
    if (const auto resolved = resolve_anthropic_options(options); resolved.has_value()) {
        options.anthropic = *resolved;
        options.anthropic->api_key.clear();
    }
    if (const auto resolved = resolve_gemini_options(options); resolved.has_value()) {
        options.gemini = *resolved;
        options.gemini->api_key.clear();
    }
    if (const auto resolved = resolve_compatible_options(options); resolved.has_value()) {
        options.compatible = *resolved;
        options.compatible->api_key.clear();
    }
    return options;
}

std::string_view to_string(const AssistantBackend backend) noexcept {
    switch (backend) {
    case AssistantBackend::Heuristic:
        return "heuristic";
    case AssistantBackend::OpenAI:
        return "openai";
    case AssistantBackend::Anthropic:
        return "anthropic";
    case AssistantBackend::Gemini:
        return "gemini";
    case AssistantBackend::OpenAICompatible:
        return "openai_compatible";
    case AssistantBackend::LocalLLM:
        return "local_llm";
    case AssistantBackend::Auto:
    default:
        return "auto";
    }
}

}  // namespace zara::ai
